name: Deploy React App to GitHub Pages with Action

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get environment variables
        uses: Sumit007521/getEnvVars@feature/update
        with:
            env_name: "production"
            gh_token: ${{ vars.GH_TOKEN }}
            file_type: "env"    

      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          node-version: $NODE_VERSION
          registry-url: $NPM_REGISTRY_URL

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: $NPM_TOKEN

      - name: Check Linting
        run: $LINT_COMMAND
        env:
          ESLINT_CONFIG_PATH: $ESLINT_CONFIG_PATH
          PRETTIER_CONFIG_PATH: $PRETTIER_CONFIG_PATH

      - name: Build React app
        run: $BUILD_COMMAND
        env:
          # Build Configuration
          CI: $CI
          NODE_ENV: $NODE_ENV
          PORT: $PORT
        
          # App Configuration
          REACT_APP_NAME: $REACT_APP_NAME
          REACT_APP_DESCRIPTION: $REACT_APP_DESCRIPTION
          REACT_APP_VERSION: $REACT_APP_VERSION
          PRICE: $PRICE
          PIZZA_DESCRIPTION: $PIZZA_DESCRIPTION
        
          # API Configuration
          REACT_APP_API_URL: $REACT_APP_API_URL
          REACT_APP_API_KEY: $REACT_APP_API_KEY
          REACT_APP_API_TIMEOUT: $REACT_APP_API_TIMEOUT
        
          # Analytics Configuration
          REACT_APP_ANALYTICS_ID: $REACT_APP_ANALYTICS_ID
          REACT_APP_ENABLE_ERROR_REPORTING: $REACT_APP_ENABLE_ERROR_REPORTING
        
          # Social Media Integration
          REACT_APP_SOCIAL_SHARING_URL: $REACT_APP_SOCIAL_SHARING_URL  
          GENERATE_SOURCEMAP: $GENERATE_SOURCEMAP
          MINIMIZE_BUILD: $MINIMIZE_BUILD
          ANALYZER_MODE: $ANALYZER_MODE

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./$BUILD_DIR

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
