name: Export Other Repo ENV Vars

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get environment variables
      uses: Sumit007521/getEnvVars@feature/update
      with:
        repo: 'Sumit007521/MyProject'
        env_name: "development"
        gh_token: ${{ vars.GH_TOKEN }}  
        file_type: "env" 

    - name: List Files
      shell: bash 
      run: ls

    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: env_var
        path: |
            env_var.json 
            env_var.txt        